name: Generate 3D Contribution Chart

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    name: Generate 3D Chart
    steps:
      - uses: actions/checkout@v3

      - name: Generate 3D profile chart
        uses: yoshi389111/github-profile-3d-contrib@latest
        with:
          github_user_name: ChaoticPost
          outputs: |
            dist/profile-3d-contrib/profile-customize.svg

      - name: Push the generated files to the output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
